Resources:
  usersTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "email"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "email"
            KeyType: "HASH"
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}