service: bootcamp-classroom-api

plugins: 
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline-ssm
  - serverless-offline

package:
  excludeDevDependencies: true
  individually: true

provider: 
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, "us-east-2"}
  stage: ${opt:stage, "local"}
  timeout: 30
  environment: ${file(./aws/env.yaml):environment}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource: 'arn:aws:dynamodb:us-east-2:*:*'
        - Effect: Allow
          Action: 
            - s3:GetObject
            - s3:PutObject
          Resource: '*'
  apiGateway:
    restApiId: !Ref MainApi
    restApiRootResourceId: !GetAtt MainApi.RootResourceId

custom:
  service: ${self:service}
  base: ${self:provider.stage}-${self:service}
  dynamodb:
    stages:
      - local
    start: 
      port: 4000
      inMemory: true
      migrate: true
      seed: true
    seed:
      tables:
        sources:
          - table: ${self:provider.stage}-${self:service}-users
            sources: [./src/seeds/users.json]
          - table: ${self:provider.stage}-${self:service}-homeworks
            sources: [./src/seeds/homeworks.json]
          - table: ${self:provider.stage}-${self:service}-homeworkSubmissions
            sources: [./src/seeds/homeworkSubmissions.json]
          - table: ${self:provider.stage}-${self:service}-subjects
            sources: [./src/seeds/subjects.json]
  esbuild:
    bundle: true
    minify: true
    exclude: ['aws-sdk']
    target: node20
    concurrency: 10
    watch:
      pattern: ['src/**/*.ts']
  serverless-offline:
    useChildProcesses: true
  serverless-offline-ssm:
    stages:
      - local

resources:
  - '${file(./aws/dynamodb.yaml)}'
  - '${file(./aws/apigateway.yaml)}'

functions:
  login:
      name: ${self:custom.base}-login
      description: 'login function'
      handler: src/handlers/login.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/login.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      events:
        - http:
            path: /login
            method: post
            cors: true 
  addStudent:
    name: ${self:custom.base}-addStudent
    description: 'addStudent function'
    handler: src/handlers/addStudent.handler
    timeout: 30
    memorySize: 264
    package:
      patterns:
        - '!src/**'
        - 'src/handlers/addStudent.*'
        - 'src/constants.*'
        - 'src/dynamodb/*'
        - 'src/helpers/**/*'
    events:
      - http:
          path: /addStudent
          method: post
          cors: true
  homework:
      name: ${self:custom.base}-homework
      description: 'homework function'
      handler: src/handlers/homework.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/homework.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      events:
        - http:
            path: /homework/{homeworkId?}
            method: get
            cors: true
  teacher:
      name: ${self:custom.base}-teacher
      description: 'teacher function'
      handler: src/handlers/subjects/teacher.handler
      timeout: 30
      memorySize: 264
      environment:
        TOKEN_SECRET: 'PARANGARICUTIRIMICUARO'
      package:
        patterns:
          - '!src/**'
          - 'src/handlers//subjects/teacher.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      events:
        - http:
            path: /subjects/teacher/{teacherEmail?}
            method: get
            cors: true