export const USER_TYPES = {
    TEACHER: "TEACHER",
    STUDENT: "STUDENT"
}
export const HTTP_CODES = {
    SUCCESS: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404
}
